[env]
term = "xterm-256color"

[window]
dynamic_title = true
opacity = 0.95
blur = false
decorations_theme_variant = "None"
decorations = "Buttonless"
option_as_alt = "OnlyLeft"
dynamic_padding = true

[window.padding]
x = 5
y = 2

[scrolling]
history = 10000
multiplier = 3

[cursor]
blink_interval = 500

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[colors.primary]
foreground = "#d6deeb"
background = "#011627"

[colors.selection]
text = "#ffffff"
background = "#1d3b53"

[colors.cursor]
text = "#011627"
cursor = "#80a4c2"

[colors.normal]
black = "#011627"
red = "#ef5350"
green = "#22da6e"
yellow = "#addb67"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#21c7a8"
white = "#ffffff"

[colors.bright]
black = "#575656"
red = "#ef5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#7fdbca"
white = "#ffffff"

[colors.dim]
black = "#011627"
red = "#ef5350"
green = "#22da6e"
yellow = "#addb67"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#21c7a8"
white = "#ffffff"
